version: '3.8'
services:
  backend:
    build:
      context: ./backend
    ports:
      - '3000:3000'
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/barber_app
    depends_on:
      - db
  frontend:
    build:
      context: ./frontend
    ports:
      - '3001:3000'
  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=barber_app
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
volumes:
  postgres_data:
